services:

  be_siconv_valida :
    image: python:3.11
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./app:/app
    depends_on:
      db_siconv_valida:
        condition: service_healthy
    network_mode: host
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&  flask run --host=0.0.0.0 --debug"


  db_siconv_valida:
    image: postgres:14.2
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    command: >
      -c min_wal_size=1GB
      -c max_wal_size=4GB
    volumes:
      - ./database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    network_mode: host
